server:
  port: 8088
  servlet:
    context-path: /interfaces

# mysql
mini-db-router:
  jdbc:
    datasource:
      dbCount: 2
      tbCount: 4
      default: db00
      routerKey: uId
      list: db01,db02
      db00:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://124.221.25.145:3306/lottery?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 13379895997.hui
      db01:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://124.221.25.145:3306/lottery_01?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 13379895997.hui
      db02:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://124.221.25.145:3306/lottery_02?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 13379895997.hui

# dubbo
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://124.221.25.145:3306/lottery?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 13379895997.hui
dubbo:
  registry:
    address: zookeeper://124.221.25.145:2181
  application:
    name: Lottery
    version: 1.0
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.kevin.lottery.rpc
mybatis-plus:
  config-location: classpath:/mybatis/config/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

# kafka
spring:
  kafka:
    bootstrap-servers: 124.221.25.145:9092
    producer:
      # 发生错误后，消息重发的次数。
      retries: 1
      #当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
      batch-size: 16384
      # 设置生产者内存缓冲区的大小。
      buffer-memory: 33554432
      # 键的序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 值的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # acks=0 ： 生产者在成功写入消息之前不会等待任何来自服务器的响应。
      # acks=1 ： 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks=all ：只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应。
      acks: 1
    consumer:
      # 自动提交的时间间隔 在spring boot 2.X 版本中这里采用的是值的类型为Duration 需要符合特定的格式，如1S,1M,2H,5D
      auto-commit-interval: 1S
      # 该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
      # latest（默认值）在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
      # earliest ：在偏移量无效的情况下，消费者将从起始位置读取分区的记录
      auto-offset-reset: earliest
      # 是否自动提交偏移量，默认值是true,为了避免出现重复数据和数据丢失，可以把它设置为false,然后手动提交偏移量
      enable-auto-commit: false
      # 键的反序列化方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 值的反序列化方式
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 5
    listener:
      # 在侦听器容器中运行的线程数。
      concurrency: 5
      #listner负责ack，每调用一次，就立即commit
      ack-mode: manual_immediate
      missing-topics-fatal: false
  redis:
    host: 124.221.25.145
    database: 0
    timeout: 3000
    port: 6379

# xxl-job
xxl:
  job:
    admin:
      addresses: http://124.221.25.145:7397/xxl-job-admin
      username: admin
      password: 123456
    executor:
      appname: lottery-job
      port: 9998
      logpath: D:\dev\project\xiaofuge\Lottery\code\LotteryMarketing\Lottery\docs\logs
      logretentiondays: 50
      ip: 124.221.25.145
    accessToken: default_token